### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by hardys**
This adds some more usage information based on additions from #23 which was recently closed

Co-Authored-By: Mangirdas Judeikis <mangirdas@judeikis.lt>

### CODE REVIEW

**Comment by hardys** [comment]
/cc @mjudeikis @s-urbaniak 

I noticed https://github.com/kcp-dev/helm-charts/pull/23 had some useful additions to the readme and a values example, so I made some similar changes here

**Comment by mjudeikis** [comment]
I will check it out during weekend. Had way more in my other fork too :) thanks!

**Comment by cychiang** [comment]
Hi! I'm trying to deploy `kcp` to a `kind` cluster but it seems missing some important parts, like: 
- `s.Options.Extra.ShardVirtualWorkspaceCAFile`, not sure where to import this file. 
- `"command failed" err="--shards-kubeconfig is required"` when starting a `kcp-front-proxy`

Not sure how to solve it and continue to make it works. Could you point me some ways to work on? Thanks!

**Comment by mjudeikis** [comment]
@hardys this looks good enough. 
Its not part of this PR, but I would change these things if possible (sorry, late to the review train on previous PR):

`- --shard-virtual-workspace-ca-file=/etc/kcp/tls/server-client/ca.crt` is missing in KCP pod spec

and I would change this as this allow rapid dev deployment into KIND without need to have proper DNS configured (will add how to get it running in follow-up PR)
image

OR we can just merge this and I will do follow-up PR with my proposed changes :) Your call

/lgtm

**Review by mjudeikis — APPROVED** [review]

**Comment by hardys** [comment]
> - --shard-virtual-workspace-ca-file=/etc/kcp/tls/server-client/ca.crt is missing in KCP pod spec

That should not be required since https://github.com/kcp-dev/kcp/pull/2659 (for now I remove the standalone VW option from the templates, until we resolve issues discussed via https://github.com/kcp-dev/kcp/pull/2672) - can you confirm which KCP image you're using?

**Review by s-urbaniak — APPROVED** [review]

**Comment by hardys** [comment]
> Hi! I'm trying to deploy `kcp` to a `kind` cluster but it seems missing some important parts, like:
> 
>     * `s.Options.Extra.ShardVirtualWorkspaceCAFile`, not sure where to import this file.
> 
>     * `"command failed" err="--shards-kubeconfig is required"` when starting a `kcp-front-proxy`
> 
> 
> Not sure how to solve it and continue to make it works. Could you point me some ways to work on? Thanks!

@cychiang please check you have the latest version of the chart - the `shards-kubeconfig` issue was resolved in #24 - if you still have issues after pulling the latest, please open an issue with more details, thanks!

**Comment by hardys** [comment]
@ncdc or @s-urbaniak perhaps you could merge this and we'll deal with any further additions as follow-ups?

**Comment by ncdc** [comment]
@hardys you have merge permissions now

**Comment by cychiang** [comment]
@hardys Thanks, I will give it a try.

**Pull request merged**
